Repository rejuvenate/lovelace-horizon-card, pull requests merged in 2024-10, with the labels that each got.

#88 Disable default release-on-push action
  .github/workflows/release.yaml
Labels: norelease

#144 Flip sunrise/sunset & dusk/dawn when southern_flip is true
  README.md
  src/components/horizonCard/HorizonCardFooter.ts
  src/components/horizonCard/HorizonCardHeader.ts
Labels: release:minor

#136 Create ur.json
  README.md
  src/assets/localization/languages/ur.json
  src/constants.ts
Labels: release:patch
